sudo: required
services:
  - docker

bofore_install:
  - docker build -t tarabet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tarabet/react-test npm test

after_success:
  - docker build -t tarabet/multi-client ./client
  - docker build -t tarabet/multi-nginx ./nginx
  - docker build -t tarabet/multi-server ./server
  - docker build -t tarabet/multi-worker ./worker
  - echo "$DOCKER_TOKEN_TRAVIS_CI" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tarabet/multi-client
  - docker push tarabet/multi-nginx
  - docker push tarabet/multi-server
  - docker push tarabet/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-711190079749
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
